name: UI and API Tests

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      testType:
        description: Select test type
        required: true
        default: all
        type: choice
        options:
          - all
          - ui
          - api
          - smoke

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 21

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Run all tests
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.testType == 'all' }}
        run: mvn clean test -Dbrowser=chrome -Dheadless=true -DapiKey=${{ secrets.REQRES_API_KEY }}

      - name: Run UI tests
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.testType == 'ui' }}
        run: mvn clean test -Pui -Dbrowser=chrome -Dheadless=true -DapiKey=${{ secrets.REQRES_API_KEY }}

      - name: Run API tests
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.testType == 'api' }}
        run: mvn clean test -Papi -DapiKey=${{ secrets.REQRES_API_KEY }}

      - name: Run smoke tests
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.testType == 'smoke' }}
        run: mvn clean test -Dtest=TestRunner -Dcucumber.filter.tags="@smoke" -Dbrowser=chrome -Dheadless=true -DapiKey=${{ secrets.REQRES_API_KEY }}

      - name: Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline
          allure generate target/allure-results -o allure-report --clean

      - name: Upload Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: |
            target/cucumber-report.html
            target/cucumber-report.json
            target/surefire-reports